### ISSUE TITLE
Cannot read property 'Api' of undefined

### ISSUE THREAD

**Issue by cizgidekiadam** [maca88/datatables.plugins#22]
I'm trying to use dt with model data.
when page loads, there was an error:
Uncaught TypeError: Cannot read property 'Api' of undefined on line dataTables.angular.js:887

**Comment by maca88** [comment]
Hello,

I'm assuming that you want use datatables with angular. 
[Here](http://live.datatables.net/IroN/238) is a simple example how to bind a collection to the table.

**Comment by wagnerdelima** [comment]
I cannot figure out how to solve that issue. Any help?

**Comment by maca88** [comment]
Did you included dataTables.js before dataTables.angular.js in your page?

**Comment by wagnerdelima** [comment]
I did. Actually I resolved the problem by getting the documentation of datatables straight. Thank you @maca88
